= OpenSSH Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:openssh: https://www.openssh.com/[OpenSSH]

System configuration for {OpenSSH} servers and clients.

== Usage

This repository contains the configuration files for {OpenSSH}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.

. Install {just} by following the instructions in the https://github.com/casey/just?tab=readme-ov-file#installation[installation section].

. Clone this repository.
+
[,sh]
----
git clone https://github.com/jwillikers/openssh-config.git
----

. Run `just install` to install the configuration.
+
[,sh]
----
just install
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2023-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
